/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RectangleDimensions = IDL.Record({ 'width' : IDL.Float64 });
export const Shape = IDL.Variant({
  'rectangle' : RectangleDimensions,
  'square' : IDL.Null,
});

export const idlService = IDL.Service({
  'areaFromRotations' : IDL.Func(
      [IDL.Float64, IDL.Float64, Shape],
      [IDL.Float64],
      [],
    ),
  'calculateIrregularArea' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64))],
      [IDL.Float64],
      [],
    ),
  'calculatePerimeter' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Float64],
      [],
    ),
  'calculateRectangleArea' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Float64],
      [],
    ),
  'calculateSquareArea' : IDL.Func([IDL.Float64], [IDL.Float64], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RectangleDimensions = IDL.Record({ 'width' : IDL.Float64 });
  const Shape = IDL.Variant({
    'rectangle' : RectangleDimensions,
    'square' : IDL.Null,
  });
  
  return IDL.Service({
    'areaFromRotations' : IDL.Func(
        [IDL.Float64, IDL.Float64, Shape],
        [IDL.Float64],
        [],
      ),
    'calculateIrregularArea' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64))],
        [IDL.Float64],
        [],
      ),
    'calculatePerimeter' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Float64],
        [],
      ),
    'calculateRectangleArea' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Float64],
        [],
      ),
    'calculateSquareArea' : IDL.Func([IDL.Float64], [IDL.Float64], []),
  });
};

export const init = ({ IDL }) => { return []; };